Add Faker rejected reasons
DFE-Digital/manage-teacher-training-applications-prototype pull request #252
Opened 2020-11-20 14:45 UTC by simonwhatley

2020-11-20 15:23 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'application-quality-reasons-subject-knowledge': 'Didn’t know enough about maths',
Did not?

2020-11-20 15:25 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'missing-qualifications-reasons-other': 'Another reason goes here'
Generate a reason with faker or a better one than this.

2020-11-20 15:25 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'application-quality-reasons-other-improve': 'Ways to improve goes here',
Generate a reason with faker or a better one than this.

2020-11-20 15:26 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'interview-performance-advice': 'Advice goes here'
Generate a reason with faker or a better one than this.

2020-11-20 15:26 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'other-offer-details': 'Other course details go here'
Generate a reason with faker or a better one than this.

2020-11-20 15:26 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'honesty-reasons-false-information': 'False information detail goes here',
Generate a reason with faker or a better one than this.

2020-11-20 15:26 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'honesty-reasons-plagiarism': 'Plagiarism detail goes here',
Generate a reason with faker or a better one than this.

2020-11-20 15:26 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'honesty-reasons-reference-information': 'Reference information goes here',
Generate a reason with faker or a better one than this.

2020-11-20 15:26 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'honesty-reasons-other': 'Another reason goes here'
Generate a reason with faker or a better one than this.

2020-11-20 15:26 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'safeguarding-reasons-vetting-information': 'Reasons the candidate unsuitable to work with children'
Generate a reason with faker or a better one than this.

2020-11-20 15:26 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'other-feedback-details': 'Additional feedback goes here'
Generate a reason with faker or a better one than this.

2020-11-20 15:27 UTC, adamsilver commented on app/data/generators/rejection.js
> +    'future-applications-details': 'Be happy to consider again'
There shouldn't be any details for this. Where did you get this from?

2020-11-20 15:28 UTC, adamsilver requested changes
Left comments inline.

2020-11-23 09:15 UTC, simonwhatley reviewed
Changes made as requested

2020-11-23 10:31 UTC, adamsilver approved these changes

2020-11-23 10:32 UTC, merged