Deferrals clean up / settings
DFE-Digital/manage-teacher-training-applications-prototype pull request #486
Opened 2021-11-11 16:32 UTC by adamsilver

2021-11-11 16:33 UTC, adamsilver commented on app/data/session-data-defaults.js
> +// const OrgHelper = require('../data/helpers/organisation')
This was in but not used, i commented out just in case.

2021-11-12 08:24 UTC, simonwhatley requested changes

2021-11-12 08:24 UTC, simonwhatley commented on scripts/generate-applications.js
> +
```suggestion
```

2021-11-12 08:24 UTC, simonwhatley commented on app/data/session-data-defaults.js
> +// defaults.settings = []
```suggestion
```

2021-11-12 08:24 UTC, simonwhatley commented on app/data/helpers/settings.js
> +
```suggestion
```

2021-11-12 08:24 UTC, simonwhatley commented on app/data/helpers/settings.js
> +
```suggestion
```

2021-11-12 08:24 UTC, simonwhatley commented on app/routes/settings.js
> +    // Turn it off
Can you elaborate on "Turn it off"?

2021-11-12 08:24 UTC, simonwhatley commented on app/views/_includes/footer.njk
> +      <div class="app-footer__cha">
Why not `app-footer__chat`?

2021-11-12 08:24 UTC, simonwhatley commented on app/views/_includes/footer.njk
> +      <div class="app-footer__emai">
Why not `app-footer__email`?

2021-11-12 08:28 UTC, simonwhatley commented on app/views/admin/settings.njk
>        Turn on start of new cycle
The title needs to change based on whether the new cycle is turned on or off. You already do this for the button, but not the title.

2021-11-12 08:28 UTC, simonwhatley commented on app/routes/settings.js
> +    res.redirect('/')
Redirecting to the applications list rather than back to the same page doesn't make it obvious you've successfully changed the settings.

2021-11-12 10:56 UTC, merged